<?php

//$channelAccessToken = 'FLPX90FqeLauLpLsrMY/hVE/B6RYCRKk6zjXDPIFa/NgMOMLLOAzf/3DcFFHLi9muxpK7qKgnUCb7XnSeaqOHGAdvPp1I+2ZxpmJnZosQ2AOXU4zWqQAkNORUgQnHOZX7DL8RjBvM+lgrbLOs+NLlwdB04t89/1O/w1cDnyilFU=';

define('CHANNEL_ACCESS_TOKEN', 'FLPX90FqeLauLpLsrMY/hVE/B6RYCRKk6zjXDPIFa/NgMOMLLOAzf/3DcFFHLi9muxpK7qKgnUCb7XnSeaqOHGAdvPp1I+2ZxpmJnZosQ2AOXU4zWqQAkNORUgQnHOZX7DL8RjBvM+lgrbLOs+NLlwdB04t89/1O/w1cDnyilFU=');

define('KEYWORD_BEAUTY', '抽');	

?>